sonar.projectKey=github-action-maven
sonar.projectName=github-action-maven
sonar.projectVersion=1.0

# Exclude all .java files from analysis
sonar.exclusions=**/*.java

# If you want to include compiled classes, you should add the target folder
sonar.java.binaries=target/classes

# Optionally, you can also add tests if you want them analyzed separately
sonar.sources=src/main
sonar.tests=src/test
